services:
  - type: web
    name: portfolio-website
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
